### ISSUE TITLE
Bonsai workflows 

### ISSUE THREAD

**Issue by ederancz** [neurogears/vestibular-vr#12]
Hi @RoboDoig. There are 2 example workflows below. 

In general, all workflows should have the following: 
1. Some sort of lab-book / metadata (time/date, animal ID, various experiment parameters e.g. gain in open loop).
2. Save processed optical sensor signals as styrofoam ball position. If using 1 optical sensor, then cumulative forward travel of the animal (say in cm) and rotation (0-360 degrees). This will of course need to be calibrated. In the future, we may want to use 2 sensors and average them for the rotation measure. 
3. Trigger and save from 1 camera. In the future, online deepLabCut analysis would be sweet and perhaps only record pupil diameter and position. 
4. A homing function. Currently using a hall-effect sensor and a magnet and rotate the platform until we activate it. 

**Workflow 1. Closed loop** 
Inputs: Target position, speed, max acceleration 
Outputs: motor command, styrofoam ball position, video 
For the future: follow arbitrary waveform as a positional command 

**Workflow 2. Open loop** 
Inputs: optical sensor signal, gain (between optical sensor and motor movement)  
Outputs: motor command, styrofoam ball position, video

Regarding motor command, we should discuss motion control fairly soon. It is a big field, and I am not well-versed in it.

**Comment by RoboDoig** [comment]
Can I assume that this issue is superseded by #49 ? Is there anything mentioned in this issue that is missing from the more recent workflow specs?

**Comment by EleonoraAmbrad** [comment]
yes, this issue can be closed!

> Can I assume that this issue is superseded by #49 ? Is there anything mentioned in this issue that is missing from the more recent workflow specs?

I think we can close this issue, thank you !
