### ISSUE TITLE
Video wall benchmarks

### ISSUE THREAD

**Issue by RoboDoig** [neurogears/vestibular-vr#23]
We need to test latency, jitter and synchronisation across screens with the matrox video wall.

- Thorlabs photodiodes
- Sampled through ONIX
- Standard closed-loop workflows for latency etc. timings
- NGR will provide workflow to be used onsite.

**Comment by ederancz** [comment]
Hey Andrew, can we close this or are you still analysing the data? Report the results here and then we can close it.

**Comment by RoboDoig** [comment]
Yes we should be able to soon, I'll upload the benchmark results here.

Do you have any kind of permanent cloud storage for lab data? Would be better to store raw data there rather than on the git repo.

**Comment by ederancz** [comment]
Good idea! 

We have a lab google drive, but I am not sure what is the easiest way for you to upload other than through the setup computer (Chrome should be logged in to ranczlab).

**Comment by RoboDoig** [comment]
Synchronisation between screens looks good, sub-millisecond

![image](https://github.com/neurogears/vestibular-vr/assets/11314305/0fb3f2a3-a3f0-4197-8a2b-1f748bbc637c)

**Comment by RoboDoig** [comment]
For latency and jitter, picture is a bit weirder. Hangs around 100ms latency. Jitter is mostly low but there are these higher latency events that pushes it up.

I would definitely expect these values to be lower, would be good to try this experiment again, also with a direct screen connection (not via Matrox) to compare.

![image](https://github.com/neurogears/vestibular-vr/assets/11314305/f0ffbe92-cf4f-452d-b734-81b19526971f)

**Comment by RoboDoig** [comment]
Poking around in the NVIDIA settings just now I also notice that there are a few options enabled that might slow down the display latency, let me know when available to repeat the test, I guess preferably after the rig has been moved.

**Comment by ederancz** [comment]
Cool, the setup won’t move before end of Jan, so Nora can set it up.-----------Sent from my phone, please excuse typos and brevity.On 22 Nov 2023, at 16:15, RoboDoig ***@***.***> wrote:﻿
Poking around in the NVIDIA settings just now I also notice that there are a few options enabled that might slow down the display latency, let me know when available to repeat the test, I guess preferably after the rig has been moved.

**Comment by RoboDoig** [comment]
Datasets for second round of benchmarks:

- Data2023_11_30_11_40_25 : Matrox only round-trip latency test
- Data2023_11_30_11_43_44: Matrox only screen-sync test

**Comment by RoboDoig** [comment]
Benchmarks with matrox only, NVIDIA ultra low latency mode, shader window focused on rig screens:

Screen_Sync:
![image](https://github.com/neurogears/vestibular-vr/assets/11314305/81edf5f5-a0cd-4a0f-84b4-765798e4cea6)

Round_Trip:
![image](https://github.com/neurogears/vestibular-vr/assets/11314305/873625fb-bb2d-49d1-ba2b-0f373cd7a06b)

I just noticed after doing this that the resolution set for the Matrox was at 7680x1080, at which the max refresh rate is 30Hz. Makes sense for the round-trip data where we are getting 1-2 frame delay at 30Hz. Will test at lower resolution with the full 60Hz, but will need someone to see what this physically looks like in the rig!

**Comment by RoboDoig** [comment]
Redid benchmarks with all monitors connected and latency jumped back up to ~100ms. @EleonoraAmbrad noticed that this was caused by Windows auto-selecting the Intel GPU as default when monitors are connected there. Fixed by forcing GPU choice to NVIDIA for the Bonsai exectuable in Windows graphics settings, Latency back down to 25-40ms.

**Comment by RoboDoig** [comment]
Added PR #34 which implements the benchmark workflows. I will merge the analysis scripts in a separate pull request, but closing this issue for now as desired latency / sync metrics achieved.
