### ISSUE TITLE
ONIX failure after NewScale runtime error

### ISSUE THREAD

**Issue by RoboDoig** [neurogears/vestibular-vr#43]
The purpose of this issue for now is to keep a record of an observed bug.

Workflows containing the NstDevice operator can produce a runtime error if no NewScale device is connected. It seems that this error also interferes with initialisation of ONIX components by Bonsai and causes the ONIX device to end up in a weird state which crashes when the workflow is reset. The hardware can be reset by running the oni-repl program.

Can't really do anything about this until the ONIX Bonsai interface is updated. For now need to make sure NewScale is connected before starting any workflows with ONIX components.

**Comment by EleonoraAmbrad** [comment]
good idea to open this issue! 

could you remind me whether the liboni repo that you used was the one we had backed up from the previous computer or if you had to build the solution on visual code starting from the newly downloaded repo? I think I missed that yesterday. Thanks!

**Comment by RoboDoig** [comment]
In the end I did not use the backed up liboni folder. I cloned the repo and built the oni-repl.exe from source.

Closing this issue in favor of #45
