### ISSUE TITLE
Update to new Bonsai.ONIX interface

### ISSUE THREAD

**Issue by RoboDoig** [neurogears/vestibular-vr#45]
Reminder issue: at some point the workflows should be updated to use the new Bonsai.ONIX interface which is currently under development. This should solve several bugs associated with ONIX being left in an unusable state without reset via oni-repl.exe with the current Bonsai interface.

**Comment by EleonoraAmbrad** [comment]
I will have a meeting with Jon this week to install the new bonsai.ONIX libraries and to set up the new headstage (NP1.0e), as the old headstage (NP1.0) will not be supported anymore. After that, I will make a new Insertion Workflow file so that it can work with the new nodes and headstage.

**Comment by EleonoraAmbrad** [comment]
I created a new insertion workflow using the NP1.0 node and the new "one context" node. However the workflow still crashes after stopping and the only way is to quit and open it again to start the acquisition. This doesn'T happen with very basic workflows that use the new libraries and nodes, so I think it has to do with the insertion workflow specifically, but I can't get my head around it. It seems to have a problem to initialise the ONI node again once the workflow has been stopped.

**Comment by EleonoraAmbrad** [comment]
Update, the insertion workflow with the new libraries and the Main experiment do not work together (I cannot run them in parallel), seems to be the same issue as above?

**Comment by RoboDoig** [comment]
Response from open-ephys regarding the harp clock is that the best solution for this is probably to update to the new ONIX interface. Therefore I'm bumping the priority of this issue as we need to have a stable synchronisation solution.

**Comment by RoboDoig** [comment]
I've updated the main workflow in the `update-onix-interface` branch. Still no sign of the HARP sync input but this may be a wiring issue, need to test when someone is available in the lab.

**Comment by RoboDoig** [comment]
Updated the interface in #78 

Tested today to see if harp sync was now working. We were not getting harp sync messages initially. After talking with open-ephys realised the clock inputs on the board are passive passthrough and there needs to be a direct clock connection to the card.

This still didn't work, but after several attempts and reconfigurations it started working after replugging the clock adapter.

Suggests to me that there is a power issue with the adapter (bad cable, port, power management on the PC), though everything is working now. Need to add something to the visualizer that monitors harp sync events so we don't lose data.

**Comment by RoboDoig** [comment]
Closing as completed with #79
