### ISSUE TITLE
Implement synchronisation between HARP and ONIX

### ISSUE THREAD

**Issue by RoboDoig** [neurogears/vestibular-vr#48]
Ideally, HARP interface of ONIX breakout will be used as a master clock for H1/H2.

Implement photodiode synchronisation on screens (flickering square to synchronise draw calls).

Use WithLatestTimestamp approach to log state changes in block state machine.

**Comment by EleonoraAmbrad** [comment]
we have a jack "stereo" cable that we can use for the synchronisation as suggested above. 

According to the design files, the harp interface signal should be split between H1 and H2, is this correct? If so, should I strip the cable and use the screw terminals on H1 and H2? 
![SignalRoutingDesign](https://github.com/neurogears/vestibular-vr/assets/143619542/50209ff6-1a8f-4c80-a445-6bba61ee1231)
![photo_2024-04-16 14 27 59](https://github.com/neurogears/vestibular-vr/assets/143619542/ac11d373-d42b-47cc-b2f1-f10b813ec53e)

**Comment by RoboDoig** [comment]
There are a couple of ways to do it, as you say you can take a stereo 3.5mm cable and have one end in H2, then bare wire in the screw terminals for H1. 

You can also get the HARP synchronizer (https://www.cf-hw.org/open-source-tools/electronic-devices/clock-synchronizer) which can act as the master clock source and has multiple output channels that you can send to H1, H2 and ONIX

**Comment by EleonoraAmbrad** [comment]
> There are a couple of ways to do it, as you say you can take a stereo 3.5mm cable and have one end in H2, then bare wire in the screw terminals for H1.
> if we were to go with this solution, how would the ONIX receive the sync signals? i.e. which connection on the breakout board should be setup?

**Comment by RoboDoig** [comment]
I don't think the ONIX can generate a HARP clock, it would rather be H2 generating the master clock and then H1 and ONIX receiving that clock. But yes, the cable would have to be split out from H2 to go to H1 and ONIX, e.g. with a 3.5mm splitter.

https://www.amazon.co.uk/PENCILUPNOSE%C2%A9-HEADPHONE-SPLITTER-EXTENSION-MOTOROLA-BLACK/dp/B079GBP6CV/ref=asc_df_B079GBP6CV/?tag=googshopuk-21&linkCode=df0&hvadid=375419269630&hvpos=&hvnetw=g&hvrand=17305413413427148390&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9046001&hvtargid=pla-1013889856952&psc=1&mcid=d37b23cc42a13f0186f1f5c3478351d8&tag=&ref=&adgrpid=85278568708&hvpone=&hvptwo=&hvadid=375419269630&hvpos=&hvnetw=g&hvrand=17305413413427148390&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9046001&hvtargid=pla-1013889856952

**Comment by EleonoraAmbrad** [comment]
update after meeting with @RoboDoig : signal should not be split between H1 and ONIX from H2, so we will instead send a randomized synchronisation ANALOG output signal to H2 and ONIX. Analog output will be generated in bonsai. 

Ideally, in the future we should rely on https://www.cf-hw.org/open-source-tools/electronic-devices/clock-synchronizer to split clock output to H2 and ONIX, especially because H2 analog input may be needed for playback signal.

**Comment by RoboDoig** [comment]
After last week's discussion: to synchronize everything correctly it will definitely be necessary to use a clock-synchronizer. The H2 analog input is occupied by the hall sensor so it can't be used as a synchronisation signal. Solution will be to have the clock-sync connected to H2 and ONIX. H2 will then pass its clock signal to H1 via the rotary joint.

**Comment by EleonoraAmbrad** [comment]
Order for the clock synchroniser will be placed this week, lead time should be 2 days.

**Comment by EleonoraAmbrad** [comment]
quick question: the HARP sync signal sent to ONIX will go in the dedicated hair sync 3.5 mm connection? this means that we would need a cable with two male audio connectors (one for the jack on clock sync and one for the ONIX?)

**Comment by ederancz** [comment]
Implemented now. There is now way to test it (would need two identical HARP devices with the same inputs), but we have no reason to believe it is not working.
