### ISSUE TITLE
ExperimentEvents log extra comma in csv

### ISSUE THREAD

**Issue by ikharitonov** [neurogears/vestibular-vr#72]
Found the following line in the ExperimentEvents CSV log file:
`439566.69075200002,Not running, skipping halt`

Not sure where the event descriptions are, could we edit this?

**Comment by RoboDoig** [comment]
Hello, event descriptions are actually currently hard-coded in string operators dotted around the workflow. Simplest solution would be to just remove the comma from this particular string but we could also think of a way to set these in some config file like the schema.

**Comment by ikharitonov** [comment]
I see, thanks for clarifying

**Comment by glopesdev** [comment]
@RoboDoig just one comment for the future, if we wanted to make sure strings are valid we could also make sure we sanitise the descriptions by stripping away all commas before logging.
