### ISSUE TITLE
Motion cloud debug

### ISSUE THREAD

**Issue by EleonoraAmbrad** [neurogears/vestibular-vr#89]
Unfortunately the "index out of bound" error is still appearing. The behavior is quite interesting but it seems that the latency at which the error appears depends on specific motion cloud properties influencing the drift of the clouds so I'm wondering if the error has to do with speed of replay of the movie. 
This happens in the context of Open loop using a playback file that only has 1 value over time (400) and is 100000 values long.

**Comment by RoboDoig** [comment]
Two issues identified here:

- Seems that for certain motion cloud movies, the MaxValue for the WrapValue node is calculated incorrectly leading to an out of index error. Need to double check length of these movies and check against what the calculated value is at runtime in Bonsai.
- In RightPhaseProcession a constant 180 value is added (this is a hangover from when only gratings and their phase were needed for the corridor stimulus). 180 here corresponds to a phase offset which is inappropriate for motion clouds which uses an index. Phase procession therefore needs to be implemented slightly differently for the motion clouds stimulus.

**Comment by RoboDoig** [comment]
I realise now as well that the 180 constant could cause an index out of bound error for shorter movies.

**Comment by RoboDoig** [comment]
Closing with #90
